services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app1:
    build: .
    environment:
      DB_USER: myuser
      DB_PASSWORD: 123
      DB_NAME: mydb
      DB_HOST: db
    depends_on:
      - db

  app2:
    build: .
    environment:
      DB_USER: myuser
      DB_PASSWORD: 123
      DB_NAME: mydb
      DB_HOST: db
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
